version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: piptonita
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    environment:
      DATABASE_URL: postgres://default:default@db:5432/piptonita
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: default@admin.com
      PGADMIN_DEFAULT_PASSWORD: default
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:

